# Constants for VEX Brain programmer port configuration
VEX_BRAIN_PROGRAMMER_PORT = "/dev/serial0"
VEX_BRAIN_PROGRAMMER_PORT_BAUD_RATE = 115200
VEX_BRAIN_PROGRAMMER_PORT_TIMEOUT = 1
VEX_BRAIN_PROGRAMMER_PORT_RETRY_DELAY = 0.5
VEX_BRAIN_PROGRAMMER_PORT_BUFFER_SIZE = 300
