DRIVER_CONTROL = 1
AUTONOMOUS_CONTROL = 2
ENABLED = True
DISABLED = False

TARGET_TICK_DURATION_MS = 10
WARNING_TICK_DURATION_MS = 8

AUTONOMOUS_TIME_IN_SECONDS = 15
DRIVER_CONTROL_TIME_IN_SECONDS = 45
SKILLS_TIME_IN_SECONDS = 105
