TRANSLATION1D_IDENTIFIER = b"T1D"
TRANSLATION2D_IDENTIFIER = b"T2D"
ROTATION2D_IDENTIFIER = b"R2D"
POSE2D_IDENTIFIER = b"P2D"
VELOCITY1D_IDENTIFIER = b"V1D"
VELOCITY2D_IDENTIFIER = b"V2D"
ROTATIONAL_VELOCITY_IDENTIFIER = b"RV"

SEPERATOR = b","
